spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_yiling
    username: root
    password: abc123
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
mybatis-plus:
  global-config:
    banner: false
server:
  port: 80 #端口号
  servlet:
    encoding:
      charset: UTF-8

prop:
  upload-folder: E:/test/ #文件保存的位置和访问文件的路径不一样，访问路径需要你直接从tbl_user表里面获取